# Generated by Django 3.1.6 on 2021-02-20 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='url')),
                ('surname', models.CharField(max_length=45, verbose_name='Фамилие')),
                ('image', models.ImageField(default='players/noavatar.png', upload_to='players/', verbose_name='Фотография')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=255, verbose_name='Текст коментария')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.player', verbose_name='Статья игрока')),
            ],
            options={
                'verbose_name': 'Коментария',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['-publication_date'],
            },
        ),
    ]
